name: Streamlit Keep Alive Anti-Sleep

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping_server:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping Request to Streamlit App
        run: |
          curl -s -I "https://streamlit.app" | head -n 1
